repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: ^backend/app/.*\.py$

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: black
        language_version: python
        files: ^backend/app/.*\.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: ["--fix"]
        files: ^backend/app/.*\.py$
