"""add_reconciliation_mismatch

Revision ID: 0b709fc8a19b
Revises: bd09ecc8dd78
Create Date: 2025-12-31 11:36:31.756885

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b709fc8a19b"
down_revision: Union[str, None] = "bd09ecc8dd78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('mart_item_alias',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('mart_id', sa.Integer(), nullable=False),
    # sa.Column('item_id', sa.Integer(), nullable=False),
    # sa.Column('alias_code', sa.String(), nullable=True),
    # sa.Column('alias_name', sa.String(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=False),
    # sa.Column('created_by', sa.String(), nullable=True),
    # sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    # sa.ForeignKeyConstraint(['mart_id'], ['mart.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('mart_id', 'alias_code', name='uq_mart_alias_code'),
    # sa.UniqueConstraint('mart_id', 'alias_name', name='uq_mart_alias_name')
    # )
    # op.create_index(op.f('ix_mart_item_alias_id'), 'mart_item_alias', ['id'], unique=False)
    op.create_table(
        "reconciliation_mismatch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_item_id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column(
            "mismatch_type",
            sa.Enum(
                "IDENTITY",
                "QUANTITY",
                "UOM",
                "PRICE",
                "MISSING_ENTRY",
                "MISSING_INVOICE",
                name="mismatchtype",
            ),
            nullable=False,
        ),
        sa.Column("system_value", sa.JSON(), nullable=True),
        sa.Column("mart_value", sa.JSON(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "RESOLVED_SYSTEM",
                "RESOLVED_MART",
                "IGNORED",
                name="mismatchstatus",
            ),
            nullable=False,
        ),
        sa.Column("resolution_notes", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invoice_item_id"],
            ["invoice_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reconciliation_mismatch_batch_id"),
        "reconciliation_mismatch",
        ["batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_mismatch_id"),
        "reconciliation_mismatch",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_mismatch_invoice_item_id"),
        "reconciliation_mismatch",
        ["invoice_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_mismatch_status"),
        "reconciliation_mismatch",
        ["status"],
        unique=False,
    )
    op.alter_column(
        "batch",
        "quantity",
        existing_type=sa.NUMERIC(precision=18, scale=6),
        nullable=False,
    )
    op.alter_column(
        "inventory_txn",
        "raw_qty",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=6),
        existing_nullable=False,
    )
    op.alter_column(
        "inventory_txn",
        "base_qty",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=6),
        existing_nullable=False,
    )
    op.alter_column(
        "rejection_entries",
        "quantity",
        existing_type=sa.NUMERIC(precision=18, scale=6),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rejection_entries",
        "quantity",
        existing_type=sa.NUMERIC(precision=18, scale=6),
        nullable=True,
    )
    op.alter_column(
        "inventory_txn",
        "base_qty",
        existing_type=sa.Numeric(precision=18, scale=6),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "inventory_txn",
        "raw_qty",
        existing_type=sa.Numeric(precision=18, scale=6),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "batch",
        "quantity",
        existing_type=sa.NUMERIC(precision=18, scale=6),
        nullable=True,
    )
    op.drop_index(
        op.f("ix_reconciliation_mismatch_status"), table_name="reconciliation_mismatch"
    )
    op.drop_index(
        op.f("ix_reconciliation_mismatch_invoice_item_id"),
        table_name="reconciliation_mismatch",
    )
    op.drop_index(
        op.f("ix_reconciliation_mismatch_id"), table_name="reconciliation_mismatch"
    )
    op.drop_index(
        op.f("ix_reconciliation_mismatch_batch_id"),
        table_name="reconciliation_mismatch",
    )
    op.drop_table("reconciliation_mismatch")
    # op.drop_index(op.f('ix_mart_item_alias_id'), table_name='mart_item_alias')
    # op.drop_table('mart_item_alias')
    # ### end Alembic commands ###
