"""Add RefreshToken

Revision ID: 23667ffc96ce
Revises: 0b709fc8a19b
Create Date: 2026-01-01 13:26:42.936040

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "23667ffc96ce"
down_revision: Union[str, None] = "0b709fc8a19b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refresh_token_id"), "refresh_token", ["id"], unique=False)
    op.create_index(
        op.f("ix_refresh_token_token"), "refresh_token", ["token"], unique=True
    )
    op.drop_index(
        "ix_reconciliation_mismatch_batch_id", table_name="reconciliation_mismatch"
    )
    op.drop_index(
        "ix_reconciliation_mismatch_invoice_item_id",
        table_name="reconciliation_mismatch",
    )
    op.drop_index(
        "ix_reconciliation_mismatch_status", table_name="reconciliation_mismatch"
    )
    op.drop_table("reconciliation_mismatch")
    op.alter_column(
        "batch",
        "quantity",
        existing_type=sa.NUMERIC(precision=18, scale=6),
        nullable=False,
    )
    op.alter_column(
        "rejection_entries",
        "quantity",
        existing_type=sa.NUMERIC(precision=18, scale=6),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rejection_entries",
        "quantity",
        existing_type=sa.NUMERIC(precision=18, scale=6),
        nullable=True,
    )
    op.alter_column(
        "batch",
        "quantity",
        existing_type=sa.NUMERIC(precision=18, scale=6),
        nullable=True,
    )
    op.create_table(
        "reconciliation_mismatch",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("invoice_item_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("batch_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "mismatch_type",
            postgresql.ENUM(
                "IDENTITY",
                "QUANTITY",
                "UOM",
                "PRICE",
                "MISSING_ENTRY",
                "MISSING_INVOICE",
                name="mismatchtype",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "system_value",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "mart_value",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "confidence_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "OPEN",
                "RESOLVED_SYSTEM",
                "RESOLVED_MART",
                "IGNORED",
                name="mismatchstatus",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("resolution_notes", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "resolved_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("resolved_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["batch.id"], name="reconciliation_mismatch_batch_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["invoice_item_id"],
            ["invoice_item.id"],
            name="reconciliation_mismatch_invoice_item_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="reconciliation_mismatch_pkey"),
    )
    op.create_index(
        "ix_reconciliation_mismatch_status",
        "reconciliation_mismatch",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_reconciliation_mismatch_invoice_item_id",
        "reconciliation_mismatch",
        ["invoice_item_id"],
        unique=False,
    )
    op.create_index(
        "ix_reconciliation_mismatch_batch_id",
        "reconciliation_mismatch",
        ["batch_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_refresh_token_token"), table_name="refresh_token")
    op.drop_index(op.f("ix_refresh_token_id"), table_name="refresh_token")
    op.drop_table("refresh_token")
    # ### end Alembic commands ###
