"""update mart related columns

Revision ID: 25d63cb63168
Revises: e2df360a0a1d
Create Date: 2025-07-22 13:35:12.041185

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "25d63cb63168"
down_revision: Union[str, None] = "e2df360a0a1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
