"""update mart related column

Revision ID: 29a44a6ff2c4
Revises: 25d63cb63168
Create Date: 2025-07-22 22:00:19.375840

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "29a44a6ff2c4"
down_revision: Union[str, None] = "25d63cb63168"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_constraint("mart_company_id_fkey", "mart", type_="foreignkey")
    op.drop_constraint("user_company_id_fkey", "user", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_company_id", table_name="company")
    op.drop_table("company")
    op.add_column("mart", sa.Column("company_name", sa.String(), nullable=False))
    op.drop_column("mart", "company_id")
    op.drop_column("user", "company_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "user_company_id_fkey", "user", "company", ["company_id"], ["id"]
    )
    op.add_column(
        "mart",
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "mart_company_id_fkey", "mart", "company", ["company_id"], ["id"]
    )
    op.drop_column("mart", "company_name")
    op.create_table(
        "company",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("created_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("updated_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="company_pkey"),
        sa.UniqueConstraint("name", name="company_name_key"),
    )
    op.create_index("ix_company_id", "company", ["id"], unique=False)
    # ### end Alembic commands ###
