"""add is_active to rejection_entry

Revision ID: 307e24fa5f89
Revises: a165ec055757
Create Date: 2026-01-17 14:31:03.927844

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "307e24fa5f89"
down_revision: Union[str, None] = "a165ec055757"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rejection_entries", sa.Column("is_active", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rejection_entries", "is_active")
    # ### end Alembic commands ###
