"""add order_id to dispatch_entry

Revision ID: 62648cac2af2
Revises: b25e9574ef87
Create Date: 2026-01-14 06:13:12.022522

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62648cac2af2"
down_revision: Union[str, None] = "b25e9574ef87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dispatch_entry", sa.Column("order_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "dispatch_entry", "order", ["order_id"], ["id"])
    op.alter_column(
        "inventory_txn",
        "raw_qty",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=3),
        existing_nullable=False,
    )
    op.alter_column(
        "inventory_txn",
        "base_qty",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=3),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inventory_txn",
        "base_qty",
        existing_type=sa.Numeric(precision=10, scale=3),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "inventory_txn",
        "raw_qty",
        existing_type=sa.Numeric(precision=10, scale=3),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.drop_constraint(None, "dispatch_entry", type_="foreignkey")
    op.drop_column("dispatch_entry", "order_id")
    # ### end Alembic commands ###
