"""Add dispatch_reversal table

Revision ID: 669d30846ddb
Revises: d30ebdf7f84f
Create Date: 2026-01-01 17:53:40.612446

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "669d30846ddb"
down_revision: Union[str, None] = "d30ebdf7f84f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dispatch_reversal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dispatch_entry_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dispatch_entry_id"],
            ["dispatch_entry.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dispatch_reversal_id"), "dispatch_reversal", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dispatch_reversal_id"), table_name="dispatch_reversal")
    op.drop_table("dispatch_reversal")
    # ### end Alembic commands ###
