"""add_idempotency_record_table

Revision ID: 92f85728c643
Revises: 324bc2ce9291
Create Date: 2025-12-23 19:00:45.319792

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "92f85728c643"
down_revision: Union[str, None] = "324bc2ce9291"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("endpoint", sa.String(), nullable=False),
        sa.Column("request_hash", sa.String(), nullable=False),
        sa.Column("result_entity_type", sa.String(), nullable=False),
        sa.Column("result_entity_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "idempotency_key", "endpoint", name="uq_idempotency_key_endpoint"
        ),
    )
    op.create_index(
        op.f("ix_idempotency_record_id"), "idempotency_record", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_idempotency_record_idempotency_key"),
        "idempotency_record",
        ["idempotency_key"],
        unique=False,
    )
    op.create_index("ix_batch_item_id", "batch", ["item_id"], unique=False)
    op.create_index("ix_batch_received_at", "batch", ["received_at"], unique=False)
    op.drop_constraint("fk_batch_created_by_user", "batch", type_="foreignkey")
    op.drop_constraint(
        "fk_dispatch_entry_created_by_user", "dispatch_entry", type_="foreignkey"
    )
    op.drop_constraint("fk_invoice_created_by_user", "invoice", type_="foreignkey")
    op.drop_constraint(
        "fk_invoice_item_created_by_user", "invoice_item", type_="foreignkey"
    )
    op.drop_constraint("fk_item_created_by_user", "item", type_="foreignkey")
    op.drop_constraint(
        "fk_item_alias_created_by_user", "item_alias", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_item_conversion_map_created_by_user",
        "item_conversion_map",
        type_="foreignkey",
    )
    op.drop_constraint("fk_mart_created_by_user", "mart", type_="foreignkey")
    op.drop_constraint("fk_order_created_by_user", "order", type_="foreignkey")
    op.drop_constraint(
        "fk_rejection_entries_created_by_user", "rejection_entries", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_stockentry_created_by_user", "stockentry", type_="foreignkey"
    )
    op.drop_constraint("fk_uom_created_by_user", "uom", type_="foreignkey")
    op.drop_constraint("fk_user_created_by_user", "user", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_user_created_by_user", "user", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_uom_created_by_user", "uom", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_stockentry_created_by_user", "stockentry", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_rejection_entries_created_by_user",
        "rejection_entries",
        "user",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_order_created_by_user", "order", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_mart_created_by_user", "mart", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_item_conversion_map_created_by_user",
        "item_conversion_map",
        "user",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_item_alias_created_by_user", "item_alias", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_item_created_by_user", "item", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_invoice_item_created_by_user",
        "invoice_item",
        "user",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_invoice_created_by_user", "invoice", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_dispatch_entry_created_by_user",
        "dispatch_entry",
        "user",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_batch_created_by_user", "batch", "user", ["created_by_id"], ["id"]
    )
    op.drop_index("ix_batch_received_at", table_name="batch")
    op.drop_index("ix_batch_item_id", table_name="batch")
    op.drop_index(
        op.f("ix_idempotency_record_idempotency_key"), table_name="idempotency_record"
    )
    op.drop_index(op.f("ix_idempotency_record_id"), table_name="idempotency_record")
    op.drop_table("idempotency_record")
    # ### end Alembic commands ###
