"""update mart-order relationship

Revision ID: 9e93302593ab
Revises: 4a9b1b3c2d5e
Create Date: 2025-07-30 23:24:49.097570

"""

from typing import Sequence, Union


from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e93302593ab"
down_revision: Union[str, None] = "4a9b1b3c2d5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "item_alias_master_item_id_fkey", "item_alias", type_="foreignkey"
    )
    op.create_foreign_key(None, "item_alias", "item", ["master_item_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "item_alias", type_="foreignkey")
    op.create_foreign_key(
        "item_alias_master_item_id_fkey",
        "item_alias",
        "item",
        ["master_item_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
