"""add is_active to stock_entry

Revision ID: a165ec055757
Revises: 8a2f3c4d5e6f
Create Date: 2026-01-17 11:36:26.598100

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a165ec055757"
down_revision: Union[str, None] = "8a2f3c4d5e6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stockentry",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stockentry", "is_active")
    # ### end Alembic commands ###
