"""mart_bill_lifecycle

Revision ID: b25e9574ef87
Revises: 669d30846ddb
Create Date: 2026-01-02 20:57:43.826387

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b25e9574ef87"
down_revision: Union[str, None] = "669d30846ddb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add status with default to prevent null errors on existing rows
    op.add_column(
        "invoice",
        sa.Column("status", sa.String(), server_default="PROCESSING", nullable=False),
    )

    # Change locked_at to DateTime (plan requirement)
    op.add_column("invoice", sa.Column("locked_at", sa.DateTime(), nullable=True))
    op.add_column("invoice", sa.Column("locked_by", sa.String(), nullable=True))

    # Data Migration
    op.execute("UPDATE invoice SET status = 'VERIFIED' WHERE is_verified = true")
    op.execute("UPDATE invoice SET status = 'NEEDS_REVIEW' WHERE is_verified = false")
    # Rows created with default "PROCESSING" that were not caught above will remain PROCESSING
    # (Technically is_verified=False covers NEEDS_REVIEW)

    op.drop_column("invoice", "is_verified")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoice",
        sa.Column("is_verified", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )

    # Reverse Data Migration
    op.execute("UPDATE invoice SET is_verified = true WHERE status = 'VERIFIED'")
    op.execute("UPDATE invoice SET is_verified = false WHERE status != 'VERIFIED'")

    op.drop_column("invoice", "locked_by")
    op.drop_column("invoice", "locked_at")
    op.drop_column("invoice", "status")
    # ### end Alembic commands ###
