"""add_dispatch_reversal

Revision ID: d30ebdf7f84f
Revises: 23667ffc96ce
Create Date: 2026-01-01 17:41:06.768843

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "d30ebdf7f84f"
down_revision: Union[str, None] = "23667ffc96ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
