"""make master item id not null

Revision ID: e2df360a0a1d
Revises: c31cfd483d56
Create Date: 2025-07-22 01:17:17.138546

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e2df360a0a1d"
down_revision: Union[str, None] = "c31cfd483d56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "item_alias", "master_item_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "item_alias", "master_item_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
