from app.db.models.mart import Mart
from sqlalchemy.orm import Session
from datetime import datetime


def seed_marts(db: Session, created_by: str = "system"):

    marts = [
        Mart(
            name="KEOTA_CC_RRL",
            company_name="Reliance",
            created_by=created_by,
            updated_by=created_by,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
        ),
        Mart(
            name="SMT_BH_Bhagalpur_Kashyap_Plaza",
            company_name="Reliance",
            created_by=created_by,
            updated_by=created_by,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
        ),
        Mart(
            name="Smart_Bhabua",
            company_name="Reliance",
            created_by=created_by,
            updated_by=created_by,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
        ),
        Mart(
            name="SBZ_BH_Darbhanga_JHA_COMPLEX",
            company_name="Reliance",
            created_by=created_by,
            updated_by=created_by,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
        ),
        Mart(
            name="SP_BH_Bhagalpur_Urmila_Arcade",
            company_name="Reliance",
            created_by=created_by,
            updated_by=created_by,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
        ),
        Mart(
            name="Smart_Aurangabad",
            company_name="Reliance",
            created_by=created_by,
            updated_by=created_by,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
        ),
        Mart(
            name="RRL_CC_Veg_Mandi-_Koley",
            company_name="Reliance",
            created_by=created_by,
            updated_by=created_by,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
        ),
        Mart(
            name="RRL_Patna_CC_Mandi_VS",
            company_name="Reliance",
            created_by=created_by,
            updated_by=created_by,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
        ),
        Mart(
            name="RRL_Ranchi_Mandi_Collection_C",
            company_name="Reliance",
            created_by=created_by,
            updated_by=created_by,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
        ),
        Mart(
            name="RRL_Bakarpur_CC",
            company_name="Reliance",
            created_by=created_by,
            updated_by=created_by,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
        ),
        Mart(
            name="SP_BH_Samastipur_Dalsingsarai",
            company_name="Reliance",
            created_by=created_by,
            updated_by=created_by,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
        ),
        Mart(
            name="Smart_Dwarika_City_Center_Muza",
            company_name="Reliance",
            created_by=created_by,
            updated_by=created_by,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
        ),
        Mart(
            name="SP_BH_Bhagalpur_Khanjarpur",
            company_name="Reliance",
            created_by=created_by,
            updated_by=created_by,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
        ),
        Mart(
            name="Smart_Bhabua",
            company_name="Reliance",
            created_by=created_by,
            updated_by=created_by,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
        ),
        Mart(
            name="SP_BH_Banka_Central_Mall",
            company_name="Reliance",
            created_by=created_by,
            updated_by=created_by,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
        ),
        Mart(
            name="Darbhanga",
            company_name="Zomato",
            created_by=created_by,
            updated_by=created_by,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
        ),
    ]
    for m in marts:
        existing = (
            db.query(Mart).filter_by(name=m.name, company_name=m.company_name).first()
        )
        if not existing:
            db.add(m)
    db.commit()
